=== ssteku/ClusterRendering/src/XMLParser/scene.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="scene" type="sceneInterface"/>

	<xs:complexType name="sceneInterface">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="camera" type="cameraInterface" maxOccurs="1" minOccurs="1" />
			<xs:element name="light" type="lightInterface"/>
			<xs:element name="sphere" type="sphereInterface"/>
			<xs:element name="elipsoid" type="elipsoidInterface"/>
			<xs:element name="plane" type="planeInterface"/>
		</xs:choice>
		<xs:attribute name="frames" type="xs:integer" use="required"/>
		<xs:attribute default="800" name="width" type="xs:integer"/>
		<xs:attribute default="600" name="height" type="xs:integer"/>
		<xs:attribute name="w" type="xs:float" use="required"/>
		<xs:attribute name="h" type="xs:float" use="required"/>
		<xs:attribute name="d" type="xs:float" use="required"/>
		<xs:attribute name="bred" type="xs:float" default="0.5" />
		<xs:attribute name="bgreen" type="xs:float" default="0.5" />
		<xs:attribute name="bblue" type="xs:float" default="0.5" />
		<xs:attribute name="glred" type="xs:float" default="0.5" />
		<xs:attribute name="glgreen" type="xs:float" default="0.5" />
		<xs:attribute name="glblue" type="xs:float" default="0.5" />
	</xs:complexType>

	<xs:complexType name="cameraInterface">
		<xs:complexContent>
			<xs:extension base="tweenInterface">
				<xs:attribute name="id" type="xs:string" use="required"/>
				<xs:attribute name="x" type="xs:float" use="required"/>
				<xs:attribute name="y" type="xs:float" use="required"/>
				<xs:attribute name="z" type="xs:float" use="required"/>
				<xs:attribute default="0" name="vx1" type="xs:float"/>
				<xs:attribute default="0" name="vy1" type="xs:float"/>
				<xs:attribute default="0" name="vz1" type="xs:float"/>
				<xs:attribute default="0" name="vx2" type="xs:float"/>
				<xs:attribute default="0" name="vy2" type="xs:float"/>
				<xs:attribute default="0" name="vz2" type="xs:float"/>
				<xs:attribute default="0" name="vx3" type="xs:float"/>
				<xs:attribute default="0" name="vy3" type="xs:float"/>
				<xs:attribute default="0" name="vz3" type="xs:float"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="sphereInterface">
		<xs:complexContent>
			<xs:extension base="objectInterface">
				<xs:attribute name="r" type="xs:float" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="elipsoidInterface">
		<xs:complexContent>
			<xs:extension base="objectInterface">
				<xs:attribute name="a" type="xs:float" use="required"/>
				<xs:attribute name="b" type="xs:float" use="required"/>
				<xs:attribute name="c" type="xs:float" use="required"/>
				<xs:attribute default="0" name="vx" type="xs:float"/>
				<xs:attribute default="0" name="vy" type="xs:float"/>
				<xs:attribute default="0" name="vz" type="xs:float"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="planeInterface">
		<xs:complexContent>
			<xs:extension base="objectInterface">
				<xs:attribute default="0" name="vx" type="xs:float"/>
				<xs:attribute default="0" name="vy" type="xs:float"/>
				<xs:attribute default="0" name="vz" type="xs:float"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="objectInterface">
		<xs:complexContent>
			<xs:extension base="colorInterface">
				<xs:attribute name="id" type="xs:string" use="required"/>
				<xs:attribute name="x" type="xs:float" use="required"/>
				<xs:attribute name="y" type="xs:float" use="required"/>
				<xs:attribute name="z" type="xs:float" use="required"/>
				<xs:attribute name="n" type="xs:integer" default="200" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="lightInterface">
		<xs:complexContent>
			<xs:extension base="colorInterface">
				<xs:attribute name="id" type="xs:string" use="required"/>
				<xs:attribute name="r" type="xs:float" use="required"/>
				<xs:attribute name="x" type="xs:float" use="required"/>
				<xs:attribute name="y" type="xs:float" use="required"/>
				<xs:attribute name="z" type="xs:float" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="colorInterface">
		<xs:complexContent>
			<xs:extension base="tweenInterface">
				<xs:attribute name="ared" type="xs:float" default="0.5" />
				<xs:attribute name="agreen" type="xs:float" default="0.5" />
				<xs:attribute name="ablue" type="xs:float" default="0.5" />

				<xs:attribute name="dred" type="xs:float" default="0.5" />
				<xs:attribute name="dgreen" type="xs:float" default="0.5" />
				<xs:attribute name="dblue" type="xs:float" default="0.5" />

				<xs:attribute name="sred" type="xs:float" default="0.5" />
				<xs:attribute name="sgreen" type="xs:float" default="0.5" />
				<xs:attribute name="sblue" type="xs:float" default="0.5" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="tweenInterface">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="tween">
				<xs:complexType>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="linear"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>

					<xs:attribute name="property" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="x"/>
								<xs:enumeration value="y"/>
								<xs:enumeration value="z"/>
								
								<xs:enumeration value="vx" />
								<xs:enumeration value="vy" />
								<xs:enumeration value="vz" />
								
								<xs:enumeration value="vx1" />
								<xs:enumeration value="vx2" />
								<xs:enumeration value="vx3" />
								
								<xs:enumeration value="vy1" />
								<xs:enumeration value="vy2" />
								<xs:enumeration value="vy3" />
								
								<xs:enumeration value="vz1" />
								<xs:enumeration value="vz2" />
								<xs:enumeration value="vz3" />
								
								<xs:enumeration value="ared" />
								<xs:enumeration value="agreen" />
								<xs:enumeration value="ablue" />
								
								<xs:enumeration value="dred" />
								<xs:enumeration value="dgreen" />
								<xs:enumeration value="dblue" />
								
								<xs:enumeration value="sred" />
								<xs:enumeration value="sgreen" />
								<xs:enumeration value="sblue" />
								
								<xs:enumeration value="n" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>

					<xs:attribute name="from" type="xs:float" use="required"/>

					<xs:attribute name="to" type="xs:float" use="required"/>

					<xs:attribute name="start" type="xs:integer" use="required"/>

					<xs:attribute name="end" type="xs:integer" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ssteku/ClusterRendering/inputs/enlargedboxes.xml
<?xml version="1.0" encoding="UTF-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" bblue="0.0" bgreen="0.0" bred="0.0" d="20" fps="24" frames="1" glblue="0.15" glgreen="0.380" glred="0.054" h="5.4" height="1080" w="9.6" width="1920" xsi:noNamespaceSchemaLocation="scene.xsd" antyalias="1">
	<camera id="camera1" vx1="1.0" vx2="0" vx3="0" vy1="0" vy2="1.0" vy3="0" vz1="0" vz2="0" vz3="1.0" x="0" y="0" z="19.941"/>
	<sphere phongN="1" blinnN="10000" ablue="0.88" agreen="0.21" ared="0.24" dblue="0.9" dgreen="0.170" dred="0.07" id="Layer 0 - Sphere" n="0.5" r="1.2" sblue="0.9" sgreen="0.0" sred="0.13"  x="0" y="0" z="0">	
	</sphere>

	<sphere phongN="1" blinnN="10000" ablue="0.28" agreen="0.51" ared="0.34" dblue="0.1" dgreen="0.570" dred="0.47" id="Layer 0 - Sphere" n="0.999" r="1" sblue="0.19" sgreen="0.50" sred="0.6"  x="-3" y="0" z="0">	
	</sphere>
	
	<sphere phongN="1" blinnN="10000" ablue="0.68" agreen="0.21" ared="0.54" dblue="0.99" dgreen="0.270" dred="0.87" id="Layer 0 - Sphere" n="0.5" r="1" sblue="0.9" sgreen="0.00" sred="0.83"  x="3" y="0" z="0">	
	</sphere>
<!-- 
	<plane id="plane" x="0.0" y="2.0" z="1.0" d="40.0" ablue="0.1" agreen="0.1" ared="0.1" dblue="0.9" dgreen="0.9" dred="0.9" sblue="0.9" sgreen="0.9" sred="0.9" n="0.09" phongN="2.0" blinnN="4.0" >
	</plane> -->
	<light ablue="0.15" agreen="0.1" ared="0.14" dblue="0.15" dgreen="0.158" dred="0.18" id="Layer 9 - Light" r="0.02" sblue="0.18" sgreen="0.17" sred="0.15"  x="-3" y="12" z="-15">
	</light>
	<light id="light2" x="-30.0" y="11.0" z="14.0" r="0.02" ared="0.0" agreen="0.9" ablue="0.3" dred="0.1" dgreen="0.2" dblue="1.0" sred="0.01" sgreen="0.01" sblue="0.01" />  

	<box phongN="1" blinnN="10000" ablue="0.3" agreen="0.21" ared="0.24" dblue="0.3" dgreen="0.170" dred="0.07" id="Layer 0 - Sphere" n="0.5" sblue="0.3" sgreen="0.2" sred="0.13"  x="-12" y="0" z="-12" maxx="-9" maxy="4" maxz="-4">	
		<tween end="100" from="-12" property="z" start="0" to="-40.0" type="linear"/>
	</box>

	<box phongN="1" blinnN="2" ablue="0.3" agreen="0.21" ared="0.24" dblue="0.3" dgreen="0.170" dred="0.07" id="Layer 0 - Sphere" n="0.5" sblue="0.3" sgreen="0.2" sred="0.13"  x="9" y="0" z="-12" maxx="12" maxy="4" maxz="-4">	
	</box>


</scene>

=== ssteku/ClusterRendering/inputs/scene_second.xml
<?xml version="1.0" encoding="UTF-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" bblue="0.1" bgreen="0.1" bred="0.1" d="20" fps="24" frames="100" glblue="0.1568627450980392" glgreen="0.3803921568627451" glred="0.054901960784313725" h="5.4" height="1080" w="9.6" width="1920" xsi:noNamespaceSchemaLocation="scene.xsd" antyalias="4">
	<camera id="camera1" vx1="1.0" vx2="0" vx3="0" vy1="0" vy2="1.0" vy3="0" vz1="0" vz2="0" vz3="1.0" x="0" y="0" z="19.941666666666666"/>
	<sphere phongN="1" blinnN="10000" ablue="0.6862745098039216" agreen="0.8196078431372549" ared="0.5490196078431373" dblue="0.8" dgreen="0.47058823529411764" dred="0.5764705882352941" id="Layer 0 - Sphere" n="0.8" r="3" sblue="0.34901960784313724" sgreen="0.5098039215686274" sred="0.6392156862745098"  x="0" y="0" z="0">
		<tween end="100" from="0" property="z" start="0" to="-15" type="linear"/>
		<tween end="100" from="0" property="y" start="0" to="-15" type="linear"/>
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.17647058823529413" agreen="0.403921568627451" ared="0.8901960784313725" dblue="0.08627450980392157" dgreen="0.1411764705882353" dred="0.8901960784313725" id="Layer 1 - Sphere" n="0.5" r="0.5" sblue="0.07058823529411765" sgreen="0.8901960784313725" sred="0.796078431372549"  x="-3" y="-3" z="0">
				
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.9294117647058824" agreen="0.8" ared="0.8862745098039215" dblue="0.8392156862745098" dgreen="0.5764705882352941" dred="0.44313725490196076" id="Layer 2 - Sphere" n="0.5" r="0.5" sblue="0.5686274509803921" sgreen="0.8392156862745098" sred="0.7058823529411765"  x="3" y="3" z="0">
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.3176470588235294" agreen="0.09019607843137255" ared="1" dblue="0.8117647058823529" dgreen="0.5450980392156862" dred="0.19607843137254902" id="Layer 3 - Sphere" n="0.5" r="0.5" sblue="0.5450980392156862" sgreen="0.6901960784313725" sred="0.8784313725490196"  x="3.25" y="-3" z="0">
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.8" agreen="0.5764705882352941" ared="0.6666666666666666" dblue="0.7215686274509804" dgreen="0.27450980392156865" dred="0.6078431372549019" id="Layer 4 - Sphere" n="0.5" r="0.5" sblue="0.3411764705882353" sgreen="0.5490196078431373" sred="0.7411764705882353"  x="-3" y="3" z="0">
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.611764705882353" agreen="0.803921568627451" ared="0.9019607843137255" dblue="0.12156862745098039" dgreen="0.23137254901960785" dred="0.8588235294117647" id="Layer 5 - Sphere" n="0.5" r="0.5" sblue="0.8588235294117647" sgreen="0.3254901960784314" sred="0.7529411764705882"  x="3" y="3" z="3">
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.10196078431372549" agreen="0.4470588235294118" ared="0.5019607843137255" dblue="0.8392156862745098" dgreen="0.16862745098039217" dred="0.7058823529411765" id="Layer 6 - Sphere" n="0.5" r="0.5" sblue="0.5647058823529412" sgreen="0.7607843137254902" sred="0.6627450980392157"  x="-3" y="3" z="3">
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.07450980392156863" agreen="0.9607843137254902" ared="0.7529411764705882" dblue="0.09019607843137255" dgreen="0.34509803921568627" dred="0.9019607843137255" id="Layer 7 - Sphere" n="0.5" r="0.5" sblue="0.054901960784313725" sgreen="0.792156862745098" sred="0.9411764705882353"  x="-2.75" y="-3" z="3">
	</sphere>
	<sphere phongN="1" blinnN="10000" ablue="0.3" agreen="0.5" ared="0.1" dblue="0.1" dgreen="0.3" dred="0.2" id="Layer 8 - Sphere" n="0.5" r="0.5" sblue="0.1" sgreen="0.3" sred="0.2"  x="3" y="-3" z="3">
	</sphere>
	<light ablue="0.15686274509803921" agreen="0.117294117647058823" ared="0.140784313725490196" dblue="0.15647058823529412" dgreen="0.15843137254901961" dred="0.18196078431372549" id="Layer 9 - Light" r="0.02" sblue="0.18313725490196079" sgreen="0.17764705882352941" sred="0.15647058823529412"  x="-3" y="12" z="-15">
		<tween end="100" from="-3" property="x" start="0" to="-15" type="linear"/>
	</light>
</scene>
